/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocationDefinitions } from '../../..';
import country_code from './country_code';
import country_code_alpha_3 from './country_code_alpha_3';
import time_zone from './time_zone';

const location: LocationDefinitions = {
  country_code,
  country_code_alpha_3,
  time_zone,
};

export default location;
